<?php
// This is file installs the map data for the SpeedEuropa variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Iceland', 'Coast', 'No', 0, 316, 49, 145, 26),
	array('Faroe Islands', 'Coast', 'No', 0, 370, 124, 174, 60),
	array('Shetland Isles', 'Coast', 'No', 1, 428, 177, 201, 85),
	array('Edinburgh', 'Coast', 'Yes', 1, 368, 226, 175, 109),
	array('Liverpool', 'Coast', 'Yes', 1, 346, 280, 166, 140),
	array('London', 'Coast', 'Yes', 1, 345, 385, 166, 183),
	array('Ireland', 'Coast', 'No', 1, 262, 300, 130, 140),
	array('Portugal', 'Coast', 'Yes', 0, 109, 688, 65, 292),
	array('Spain', 'Coast', 'Yes', 0, 257, 663, 110, 307),
	array('Majorca', 'Coast', 'No', 0, 348, 711, 165, 332),
	array('North Africa', 'Coast', 'No', 0, 143, 831, 135, 390),
	array('Tunis', 'Coast', 'Yes', 0, 153, 797, 73, 375),
	array('Sardinia', 'Coast', 'No', 3, 466, 713, 220, 340),
	array('Sicily', 'Coast', 'No', 3, 533, 801, 265, 380),
	array('Naples', 'Coast', 'Yes', 3, 617, 750, 298, 357),
	array('Rome', 'Coast', 'Yes', 3, 540, 655, 272, 330),
	array('Piedmont', 'Coast', 'No', 3, 476, 586, 228, 276),
	array('Venice', 'Coast', 'Yes', 3, 628, 710, 258, 292),
	array('Greece', 'Coast', 'Yes', 0, 763, 775, 355, 361),
	array('Crete', 'Coast', 'No', 0, 845, 832, 396, 390),
	array('Albania', 'Coast', 'No', 0, 729, 716, 343, 341),
	array('Serbia', 'Land', 'Yes', 0, 760, 690, 357, 324),
	array('Thrace', 'Coast', 'No', 0, 807, 695, 395, 327),
	array('Bulgaria', 'Coast', 'Yes', 0, 861, 647, 385, 310),
	array('Walachia', 'Land', 'No', 0, 831, 617, 390, 290),
	array('Rumania', 'Coast', 'Yes', 0, 866, 558, 412, 272),
	array('Constantinople', 'Coast', 'Yes', 6, 919, 729, 433, 345),
	array('Smyrna', 'Coast', 'Yes', 6, 1050, 755, 480, 363),
	array('Ankara', 'Coast', 'Yes', 6, 1039, 663, 485, 320),
	array('Armenia', 'Coast', 'No', 6, 1161, 661, 550, 316),
	array('Syria', 'Coast', 'No', 6, 1250, 765, 559, 370),
	array('Cyprus', 'Coast', 'No', 6, 1038, 825, 488, 388),
	array('Volga', 'Land', 'No', 7, 1220, 390, 575, 175),
	array('Sevastopol', 'Coast', 'Yes', 7, 997, 532, 485, 248),
	array('Bessarabia', 'Coast', 'No', 7, 924, 543, 435, 255),
	array('Warsaw', 'Land', 'Yes', 7, 768, 442, 358, 209),
	array('Moscow', 'Land', 'Yes', 7, 895, 387, 490, 160),
	array('Siberia', 'Coast', 'No', 7, 1190, 65, 495, 40),
	array('St. Petersburg', 'Coast', 'Yes', 7, 980, 188, 445, 97),
	array('Finland', 'Coast', 'No', 7, 788, 175, 369, 109),
	array('Gotland', 'Coast', 'No', 0, 709, 319, 333, 153),
	array('Sweden', 'Coast', 'Yes', 0, 652, 220, 307, 103),
	array('Norway', 'Coast', 'Yes', 0, 587, 185, 265, 113),
	array('Denmark', 'Coast', 'Yes', 0, 572, 322, 264, 150),
	array('Schleswig-Holstein', 'Coast', 'No', 4, 557, 364, 258, 171),
	array('Kiel', 'Coast', 'Yes', 4, 536, 402, 253, 192),
	array('Berlin', 'Coast', 'Yes', 4, 615, 399, 287, 189),
	array('Prussia', 'Coast', 'No', 4, 672, 427, 319, 202),
	array('Silesia', 'Land', 'No', 4, 676, 476, 315, 222),
	array('Munich', 'Land', 'Yes', 4, 542, 497, 250, 226),
	array('Swabia', 'Land', 'No', 4, 520, 510, 232, 236),
	array('Ruhr', 'Coast', 'No', 4, 508, 430, 238, 204),
	array('Holland', 'Coast', 'Yes', 0, 498, 390, 234, 185),
	array('Belgium', 'Coast', 'Yes', 0, 456, 432, 215, 205),
	array('Picardy', 'Coast', 'No', 2, 394, 440, 204, 217),
	array('Brest', 'Coast', 'Yes', 2, 315, 501, 149, 231),
	array('Paris', 'Coast', 'Yes', 2, 364, 468, 174, 227),
	array('Burgundy', 'Land', 'No', 2, 443, 507, 200, 250),
	array('Marseilles', 'Coast', 'Yes', 2, 434, 605, 200, 285),
	array('Gascony', 'Coast', 'No', 2, 340, 560, 154, 265),
	array('Corsica', 'Coast', 'No', 2, 479, 671, 225, 315),
	array('Switzerland', 'Land', 'Yes', 0, 493, 538, 229, 252),
	array('Tyrolia', 'Coast', 'No', 5, 599, 533, 282, 252),
	array('Bohemia', 'Land', 'No', 5, 629, 488, 298, 227),
	array('Vienna', 'Land', 'Yes', 5, 681, 513, 314, 246),
	array('Trieste', 'Coast', 'Yes', 5, 641, 629, 300, 295),
	array('Bosnia', 'Land', 'No', 5, 688, 628, 332, 290),
	array('Budapest', 'Land', 'Yes', 5, 748, 550, 350, 260),
	array('Galicia', 'Land', 'No', 5, 805, 510, 378, 240),
	array('Transylvania', 'Land', 'No', 5, 800, 555, 385, 270),
	array('Barents Sea', 'Sea', 'No', 0, 876, 34, 200, 10),
	array('Norwegian Sea', 'Sea', 'No', 0, 521, 134, 275, 35),
	array('North Sea', 'Sea', 'No', 0, 484, 250, 216, 125),
	array('Heligoland Bight', 'Sea', 'No', 0, 430, 380, 205, 180),
	array('Baltic Sea', 'Sea', 'No', 0, 674, 361, 320, 177),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 734, 291, 345, 135),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 60, 245, 40, 125),
	array('English Channel', 'Sea', 'No', 0, 232, 380, 115, 185),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 0, 206, 241, 110, 100),
	array('Bay of Biscay', 'Sea', 'No', 0, 250, 520, 117, 245),
	array('Western Mediterranean', 'Sea', 'No', 0, 483, 779, 200, 365),
	array('Gulf of Lyon', 'Sea', 'No', 0, 415, 676, 203, 322),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 520, 693, 255, 340),
	array('Ionian Sea', 'Sea', 'No', 0, 700, 775, 325, 375),
	array('Adriatic Sea', 'Sea', 'No', 0, 627, 668, 306, 323),
	array('Aegean Sea', 'Sea', 'No', 0, 828, 761, 395, 363),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 676, 827, 340, 390),
	array('Gulf of Anatalya', 'Sea', 'No', 0, 982, 816, 465, 383),
	array('Black Sea', 'Sea', 'No', 0, 961, 611, 460, 300),
	array('Sea of Azov', 'Sea', 'No', 0, 1110, 625, 520, 300),
	array('Spain (North Coast)', 'Coast', 'No', 0, 167, 574, 90, 273),
	array('Spain (South Coast)', 'Coast', 'No', 0, 243, 720, 106, 345),
	array('North Africa (East Coast)', 'Coast', 'No', 0, 460, 833, 20, 390),
	array('North Africa (West Coast)', 'Coast', 'No', 0, 52, 825, 225, 395),
	array('Thrace (North Coast)', 'Coast', 'No', 0, 885, 659, 429, 313),
	array('Thrace (South Coast)', 'Coast', 'No', 0, 796, 720, 400, 333),
	array('St. Petersburg (North Coast)', 'Coast', 'No', 7, 940, 135, 430, 77),
	array('St. Petersburg (South Coast)', 'Coast', 'No', 7, 845, 275, 397, 130),
	array('Finland (North Coast)', 'Coast', 'No', 7, 794, 70, 375, 35),
	array('Finland (South Coast)', 'Coast', 'No', 7, 815, 244, 355, 105),
	array('Schleswig-Holstein (East Coast)', 'Coast', 'No', 4, 565, 371, 270, 180),
	array('Schleswig-Holstein (West Coast)', 'Coast', 'No', 4, 548, 363, 258, 177),
	array('Gascony (North Coast)', 'Coast', 'No', 2, 311, 538, 140, 255),
	array('Gascony (South Coast)', 'Coast', 'No', 2, 349, 623, 170, 295)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Iceland','Barents Sea','Yes','No'),
	array('Iceland','Norwegian Sea','Yes','No'),
	array('Iceland','North Atlantic Ocean','Yes','No'),
	array('Iceland','Mid-Atlantic Ocean','Yes','No'),
	array('Faroe Islands','Norwegian Sea','Yes','No'),
	array('Faroe Islands','Mid-Atlantic Ocean','Yes','No'),
	array('Shetland Isles','Norwegian Sea','Yes','No'),
	array('Shetland Isles','North Sea','Yes','No'),
	array('Edinburgh','Liverpool','Yes','Yes'),
	array('Edinburgh','London','Yes','Yes'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Liverpool','London','Yes','Yes'),
	array('Liverpool','Ireland','Yes','Yes'),
	array('Liverpool','Norwegian Sea','Yes','No'),
	array('Liverpool','English Channel','Yes','No'),
	array('Liverpool','Mid-Atlantic Ocean','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('London','Heligoland Bight','Yes','No'),
	array('London','English Channel','Yes','No'),
	array('Ireland','English Channel','Yes','No'),
	array('Ireland','Mid-Atlantic Ocean','Yes','No'),
	array('Portugal','Spain','No','Yes'),
	array('Portugal','Mid-Atlantic Ocean','Yes','No'),
	array('Portugal','Spain (North Coast)','Yes','No'),
	array('Portugal','Spain (South Coast)','Yes','No'),
	array('Spain','Gascony','No','Yes'),
	array('Majorca','Western Mediterranean','Yes','No'),
	array('Majorca','Gulf of Lyon','Yes','No'),
	array('North Africa','Tunis','No','Yes'),
	array('Tunis','North Atlantic Ocean','Yes','No'),
	array('Tunis','Mid-Atlantic Ocean','Yes','No'),
	array('Tunis','Western Mediterranean','Yes','No'),
	array('Tunis','Ionian Sea','Yes','No'),
	array('Tunis','Eastern Mediterranean','Yes','No'),
	array('Tunis','North Africa (East Coast)','Yes','No'),
	array('Tunis','North Africa (West Coast)','Yes','No'),
	array('Sardinia','Western Mediterranean','Yes','No'),
	array('Sardinia','Gulf of Lyon','Yes','No'),
	array('Sardinia','Tyrrhenian Sea','Yes','No'),
	array('Sicily','Naples','Yes','Yes'),
	array('Sicily','Western Mediterranean','Yes','No'),
	array('Sicily','Ionian Sea','Yes','No'),
	array('Naples','Rome','Yes','Yes'),
	array('Naples','Venice','Yes','Yes'),
	array('Naples','Western Mediterranean','Yes','No'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Rome','Piedmont','Yes','Yes'),
	array('Rome','Venice','No','Yes'),
	array('Rome','Gulf of Lyon','Yes','No'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Piedmont','Venice','No','Yes'),
	array('Piedmont','Burgundy','No','Yes'),
	array('Piedmont','Marseilles','Yes','Yes'),
	array('Piedmont','Switzerland','No','Yes'),
	array('Piedmont','Tyrolia','No','Yes'),
	array('Piedmont','Gulf of Lyon','Yes','No'),
	array('Venice','Tyrolia','Yes','Yes'),
	array('Venice','Ionian Sea','Yes','No'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Greece','Albania','Yes','Yes'),
	array('Greece','Serbia','No','Yes'),
	array('Greece','Thrace','No','Yes'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Greece','Thrace (South Coast)','Yes','No'),
	array('Crete','Ionian Sea','Yes','No'),
	array('Crete','Eastern Mediterranean','Yes','No'),
	array('Crete','Gulf of Anatalya','Yes','No'),
	array('Albania','Serbia','No','Yes'),
	array('Albania','Trieste','Yes','Yes'),
	array('Albania','Bosnia','No','Yes'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Serbia','Thrace','No','Yes'),
	array('Serbia','Bulgaria','No','Yes'),
	array('Serbia','Walachia','No','Yes'),
	array('Serbia','Bosnia','No','Yes'),
	array('Thrace','Bulgaria','No','Yes'),
	array('Thrace','Constantinople','No','Yes'),
	array('Bulgaria','Walachia','No','Yes'),
	array('Bulgaria','Rumania','Yes','Yes'),
	array('Bulgaria','Black Sea','Yes','No'),
	array('Bulgaria','Thrace (North Coast)','Yes','No'),
	array('Walachia','Rumania','No','Yes'),
	array('Walachia','Bosnia','No','Yes'),
	array('Walachia','Budapest','No','Yes'),
	array('Walachia','Transylvania','No','Yes'),
	array('Rumania','Bessarabia','Yes','Yes'),
	array('Rumania','Galicia','No','Yes'),
	array('Rumania','Transylvania','No','Yes'),
	array('Rumania','Black Sea','Yes','No'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Ankara','Yes','Yes'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Constantinople','Thrace (North Coast)','Yes','No'),
	array('Constantinople','Thrace (South Coast)','Yes','No'),
	array('Smyrna','Ankara','No','Yes'),
	array('Smyrna','Armenia','No','Yes'),
	array('Smyrna','Syria','Yes','Yes'),
	array('Smyrna','Ionian Sea','Yes','No'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Smyrna','Eastern Mediterranean','Yes','No'),
	array('Smyrna','Gulf of Anatalya','Yes','No'),
	array('Ankara','Armenia','Yes','Yes'),
	array('Ankara','Black Sea','Yes','No'),
	array('Ankara','Sea of Azov','Yes','No'),
	array('Armenia','Syria','No','Yes'),
	array('Armenia','Volga','No','Yes'),
	array('Armenia','Sevastopol','Yes','Yes'),
	array('Armenia','Sea of Azov','Yes','No'),
	array('Syria','Volga','No','Yes'),
	array('Syria','Eastern Mediterranean','Yes','No'),
	array('Cyprus','Eastern Mediterranean','Yes','No'),
	array('Cyprus','Gulf of Anatalya','Yes','No'),
	array('Volga','Sevastopol','No','Yes'),
	array('Volga','Moscow','No','Yes'),
	array('Volga','Siberia','No','Yes'),
	array('Sevastopol','Bessarabia','Yes','Yes'),
	array('Sevastopol','Moscow','No','Yes'),
	array('Sevastopol','Galicia','No','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Sevastopol','Sea of Azov','Yes','No'),
	array('Bessarabia','Galicia','No','Yes'),
	array('Bessarabia','Black Sea','Yes','No'),
	array('Warsaw','Moscow','No','Yes'),
	array('Warsaw','Prussia','No','Yes'),
	array('Warsaw','Silesia','No','Yes'),
	array('Warsaw','Galicia','No','Yes'),
	array('Moscow','Siberia','No','Yes'),
	array('Moscow','St. Petersburg','No','Yes'),
	array('Moscow','Prussia','No','Yes'),
	array('Moscow','Galicia','No','Yes'),
	array('Siberia','St. Petersburg','No','Yes'),
	array('Siberia','Barents Sea','Yes','No'),
	array('Siberia','St. Petersburg (North Coast)','Yes','No'),
	array('St. Petersburg','Finland','No','Yes'),
	array('St. Petersburg','Prussia','No','Yes'),
	array('Finland','Sweden','No','Yes'),
	array('Finland','Norway','No','Yes'),
	array('Gotland','Baltic Sea','Yes','No'),
	array('Gotland','Gulf of Bothnia','Yes','No'),
	array('Sweden','Norway','Yes','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','North Sea','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Sweden','Finland (South Coast)','Yes','No'),
	array('Norway','Barents Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Finland (North Coast)','Yes','No'),
	array('Denmark','Schleswig-Holstein','No','Yes'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Denmark','Schleswig-Holstein (East Coast)','Yes','No'),
	array('Denmark','Schleswig-Holstein (West Coast)','Yes','No'),
	array('Schleswig-Holstein','Kiel','No','Yes'),
	array('Kiel','Berlin','Yes','Yes'),
	array('Kiel','Munich','No','Yes'),
	array('Kiel','Ruhr','Yes','Yes'),
	array('Kiel','North Sea','Yes','No'),
	array('Kiel','Heligoland Bight','Yes','No'),
	array('Kiel','Baltic Sea','Yes','No'),
	array('Kiel','Schleswig-Holstein (East Coast)','Yes','No'),
	array('Kiel','Schleswig-Holstein (West Coast)','Yes','No'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Berlin','Silesia','No','Yes'),
	array('Berlin','Munich','No','Yes'),
	array('Berlin','Baltic Sea','Yes','No'),
	array('Prussia','Silesia','No','Yes'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('Prussia','St. Petersburg (South Coast)','Yes','No'),
	array('Silesia','Munich','No','Yes'),
	array('Silesia','Bohemia','No','Yes'),
	array('Silesia','Vienna','No','Yes'),
	array('Silesia','Galicia','No','Yes'),
	array('Munich','Swabia','No','Yes'),
	array('Munich','Ruhr','No','Yes'),
	array('Munich','Picardy','No','Yes'),
	array('Munich','Burgundy','No','Yes'),
	array('Munich','Tyrolia','No','Yes'),
	array('Munich','Bohemia','No','Yes'),
	array('Swabia','Swabia','No','Yes'),
	array('Swabia','Burgundy','No','Yes'),
	array('Swabia','Switzerland','No','Yes'),
	array('Swabia','Tyrolia','No','Yes'),
	array('Ruhr','Holland','Yes','Yes'),
	array('Ruhr','Belgium','No','Yes'),
	array('Ruhr','Picardy','No','Yes'),
	array('Ruhr','Burgundy','No','Yes'),
	array('Ruhr','Heligoland Bight','Yes','No'),
	array('Holland','Belgium','Yes','Yes'),
	array('Holland','Heligoland Bight','Yes','No'),
	array('Belgium','Picardy','Yes','Yes'),
	array('Belgium','Heligoland Bight','Yes','No'),
	array('Belgium','English Channel','Yes','No'),
	array('Picardy','Paris','Yes','Yes'),
	array('Picardy','Burgundy','No','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('Brest','Paris','Yes','Yes'),
	array('Brest','Gascony','No','Yes'),
	array('Brest','English Channel','Yes','No'),
	array('Brest','Mid-Atlantic Ocean','Yes','No'),
	array('Brest','Bay of Biscay','Yes','No'),
	array('Brest','Gascony (North Coast)','Yes','No'),
	array('Paris','Burgundy','No','Yes'),
	array('Paris','Gascony','No','Yes'),
	array('Paris','English Channel','Yes','No'),
	array('Burgundy','Marseilles','No','Yes'),
	array('Burgundy','Gascony','No','Yes'),
	array('Burgundy','Switzerland','No','Yes'),
	array('Marseilles','Gascony','No','Yes'),
	array('Marseilles','Gulf of Lyon','Yes','No'),
	array('Marseilles','Gascony (South Coast)','Yes','No'),
	array('Corsica','Gulf of Lyon','Yes','No'),
	array('Corsica','Tyrrhenian Sea','Yes','No'),
	array('Switzerland','Tyrolia','No','Yes'),
	array('Tyrolia','Bohemia','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrolia','Trieste','No','Yes'),
	array('Tyrolia','Adriatic Sea','Yes','No'),
	array('Bohemia','Vienna','No','Yes'),
	array('Vienna','Trieste','No','Yes'),
	array('Vienna','Budapest','No','Yes'),
	array('Vienna','Galicia','No','Yes'),
	array('Trieste','Bosnia','No','Yes'),
	array('Trieste','Budapest','No','Yes'),
	array('Trieste','Ionian Sea','Yes','No'),
	array('Trieste','Adriatic Sea','Yes','No'),
	array('Bosnia','Budapest','No','Yes'),
	array('Budapest','Galicia','No','Yes'),
	array('Budapest','Transylvania','No','Yes'),
	array('Galicia','Transylvania','No','Yes'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','North Atlantic Ocean','Yes','No'),
	array('Barents Sea','St. Petersburg (North Coast)','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','North Atlantic Ocean','Yes','No'),
	array('Norwegian Sea','Mid-Atlantic Ocean','Yes','No'),
	array('Norwegian Sea','St. Petersburg (North Coast)','Yes','No'),
	array('Norwegian Sea','Finland (North Coast)','Yes','No'),
	array('North Sea','Heligoland Bight','Yes','No'),
	array('North Sea','Schleswig-Holstein (West Coast)','Yes','No'),
	array('Heligoland Bight','English Channel','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Baltic Sea','St. Petersburg (South Coast)','Yes','No'),
	array('Baltic Sea','Schleswig-Holstein (East Coast)','Yes','No'),
	array('Gulf of Bothnia','St. Petersburg (South Coast)','Yes','No'),
	array('Gulf of Bothnia','Finland (South Coast)','Yes','No'),
	array('North Atlantic Ocean','Mid-Atlantic Ocean','Yes','No'),
	array('North Atlantic Ocean','North Africa (West Coast)','Yes','No'),
	array('English Channel','Mid-Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Bay of Biscay','Yes','No'),
	array('Mid-Atlantic Ocean','Western Mediterranean','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (North Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (South Coast)','Yes','No'),
	array('Bay of Biscay','Spain (North Coast)','Yes','No'),
	array('Bay of Biscay','Gascony (North Coast)','Yes','No'),
	array('Western Mediterranean','Gulf of Lyon','Yes','No'),
	array('Western Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Western Mediterranean','Ionian Sea','Yes','No'),
	array('Western Mediterranean','Spain (South Coast)','Yes','No'),
	array('Gulf of Lyon','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyon','Spain (South Coast)','Yes','No'),
	array('Gulf of Lyon','Gascony (South Coast)','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','Aegean Sea','Yes','No'),
	array('Ionian Sea','Eastern Mediterranean','Yes','No'),
	array('Ionian Sea','Gulf of Anatalya','Yes','No'),
	array('Aegean Sea','Gulf of Anatalya','Yes','No'),
	array('Aegean Sea','Thrace (South Coast)','Yes','No'),
	array('Eastern Mediterranean','Gulf of Anatalya','Yes','No'),
	array('Eastern Mediterranean','North Africa (East Coast)','Yes','No'),
	array('Black Sea','Sea of Azov','Yes','No'),
	array('Black Sea','Thrace (North Coast)','Yes','No'),
	array('Spain (North Coast)','Gascony (North Coast)','Yes','No'),
	array('Spain (South Coast)','Gascony (South Coast)','Yes','No'),
	array('St. Petersburg (North Coast)','Finland (North Coast)','Yes','No'),
	array('St. Petersburg (South Coast)','Finland (South Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
