<?php
// This is file installs the map data for the SouthSahara variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Akjoujt', 'Coast', 'No', 0, 135, 38, 136, 34),
	array('Waalo', 'Coast', 'No', 0, 128, 99, 132, 95),
	array('Kayor', 'Coast', 'Yes', 4, 141, 166, 143, 165),
	array('Sine', 'Coast', 'No', 4, 90, 279, 96, 280),
	array('Baol', 'Land', 'Yes', 4, 171, 220, 175, 221),
	array('Saloum', 'Land', 'Yes', 4, 158, 269, 148, 268),
	array('Wangara', 'Coast', 'Yes', 0, 190, 374, 191, 371),
	array('Bure', 'Coast', 'Yes', 0, 293, 384, 293, 386),
	array('Bambuk', 'Land', 'No', 0, 240, 311, 224, 263),
	array('Awdagost', 'Land', 'No', 0, 232, 207, 236, 187),
	array('Tichitt', 'Land', 'Yes', 0, 264, 113, 256, 105),
	array('Tavdeni', 'Land', 'No', 0, 361, 125, 371, 126),
	array('Walata', 'Land', 'Yes', 5, 342, 213, 346, 204),
	array('Kumbi Saleh', 'Land', 'Yes', 5, 283, 186, 285, 182),
	array('Niani', 'Land', 'No', 5, 288, 304, 289, 299),
	array('Jenne', 'Land', 'Yes', 5, 339, 283, 339, 275),
	array('Timbuktu', 'Land', 'Yes', 5, 396, 188, 398, 172),
	array('Tadmekka', 'Land', 'No', 5, 426, 227, 425, 219),
	array('Gao', 'Land', 'Yes', 0, 456, 219, 484, 179),
	array('Ghat', 'Land', 'No', 0, 563, 100, 586, 88),
	array('Murzuk', 'Land', 'No', 3, 808, 104, 811, 97),
	array('Tibesti', 'Land', 'No', 0, 887, 99, 901, 94),
	array('Abesehr', 'Land', 'No', 0, 949, 223, 963, 229),
	array('Ubangi', 'Land', 'No', 0, 929, 483, 964, 539),
	array('Lunda', 'Coast', 'No', 0, 752, 579, 757, 578),
	array('Kongo', 'Land', 'Yes', 0, 843, 530, 846, 532),
	array('Wouri', 'Coast', 'No', 0, 765, 498, 765, 492),
	array('Zazzau', 'Land', 'No', 0, 753, 388, 754, 391),
	array('Bouar', 'Land', 'No', 0, 843, 428, 837, 412),
	array('Masseniya', 'Land', 'Yes', 3, 885, 274, 881, 270),
	array('Bilma', 'Land', 'Yes', 3, 849, 207, 839, 202),
	array('Njimi', 'Land', 'Yes', 3, 772, 241, 758, 244),
	array('Agadez', 'Land', 'No', 0, 676, 250, 662, 245),
	array('Takedda', 'Land', 'Yes', 0, 541, 245, 534, 238),
	array('Gwandu', 'Land', 'No', 0, 478, 330, 477, 326),
	array('Oagadougou', 'Land', 'Yes', 0, 411, 324, 434, 347),
	array('Mossi', 'Land', 'No', 0, 359, 330, 380, 371),
	array('Begho', 'Coast', 'Yes', 2, 398, 412, 407, 402),
	array('Salaga', 'Land', 'Yes', 2, 442, 406, 444, 403),
	array('Bono Manso', 'Coast', 'Yes', 2, 429, 454, 514, 430),
	array('Oyo', 'Land', 'Yes', 0, 543, 355, 550, 354),
	array('Ijebu', 'Coast', 'No', 0, 600, 404, 547, 403),
	array('Edo', 'Coast', 'Yes', 1, 626, 453, 629, 436),
	array('Ife', 'Land', 'Yes', 1, 655, 401, 653, 398),
	array('Nupe', 'Land', 'No', 1, 684, 357, 665, 344),
	array('Owo', 'Coast', 'Yes', 1, 688, 464, 688, 459),
	array('Etula Eri', 'Coast', 'Yes', 0, 673, 550, 676, 549),
	array('Oasis 1', 'Land', 'No', 0, 268, 20, 270, 19),
	array('Oasis 2', 'Land', 'No', 0, 312, 20, 311, 19),
	array('Oasis 3', 'Land', 'No', 0, 353, 21, 354, 18),
	array('Oasis 4', 'Land', 'No', 0, 393, 17, 398, 17),
	array('Oasis 5', 'Land', 'No', 0, 437, 18, 436, 18),
	array('Jolof Sea', 'Sea', 'No', 0, 60, 162, 63, 155),
	array('Sea of Wangara', 'Sea', 'No', 0, 85, 395, 69, 376),
	array('Sea of Bure', 'Sea', 'No', 0, 194, 475, 207, 484),
	array('Akan Sea', 'Sea', 'No', 0, 437, 508, 447, 518),
	array('Bight of Biafra', 'Sea', 'No', 0, 597, 496, 600, 518),
	array('High Seas 1', 'Sea', 'No', 0, 43, 486, 41, 485),
	array('High Seas 2', 'Sea', 'No', 0, 57, 533, 58, 533),
	array('High Seas 3', 'Sea', 'No', 0, 102, 554, 102, 554)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Akjoujt','Waalo','Yes','Yes'),
	array('Akjoujt','Tichitt','No','Yes'),
	array('Akjoujt','Oasis 1','No','Yes'),
	array('Akjoujt','Oasis 2','No','Yes'),
	array('Akjoujt','Oasis 3','No','Yes'),
	array('Akjoujt','Oasis 4','No','Yes'),
	array('Akjoujt','Oasis 5','No','Yes'),
	array('Akjoujt','Jolof Sea','Yes','No'),
	array('Akjoujt','High Seas 1','Yes','No'),
	array('Akjoujt','High Seas 2','Yes','No'),
	array('Akjoujt','High Seas 3','Yes','No'),
	array('Waalo','Kayor','Yes','Yes'),
	array('Waalo','Tichitt','No','Yes'),
	array('Waalo','Jolof Sea','Yes','No'),
	array('Kayor','Sine','Yes','Yes'),
	array('Kayor','Baol','No','Yes'),
	array('Kayor','Saloum','No','Yes'),
	array('Kayor','Awdagost','No','Yes'),
	array('Kayor','Tichitt','No','Yes'),
	array('Kayor','Jolof Sea','Yes','No'),
	array('Kayor','Sea of Wangara','Yes','No'),
	array('Sine','Baol','No','Yes'),
	array('Sine','Saloum','No','Yes'),
	array('Sine','Wangara','Yes','Yes'),
	array('Sine','Sea of Wangara','Yes','No'),
	array('Baol','Saloum','No','Yes'),
	array('Saloum','Wangara','No','Yes'),
	array('Saloum','Bambuk','No','Yes'),
	array('Saloum','Awdagost','No','Yes'),
	array('Wangara','Bure','Yes','Yes'),
	array('Wangara','Bambuk','No','Yes'),
	array('Wangara','Sea of Wangara','Yes','No'),
	array('Wangara','Sea of Bure','Yes','No'),
	array('Bure','Bambuk','No','Yes'),
	array('Bure','Niani','No','Yes'),
	array('Bure','Jenne','No','Yes'),
	array('Bure','Mossi','No','Yes'),
	array('Bure','Begho','Yes','Yes'),
	array('Bure','Sea of Bure','Yes','No'),
	array('Bambuk','Awdagost','No','Yes'),
	array('Bambuk','Kumbi Saleh','No','Yes'),
	array('Bambuk','Niani','No','Yes'),
	array('Awdagost','Tichitt','No','Yes'),
	array('Awdagost','Kumbi Saleh','No','Yes'),
	array('Tichitt','Tavdeni','No','Yes'),
	array('Tichitt','Kumbi Saleh','No','Yes'),
	array('Tichitt','Oasis 1','No','Yes'),
	array('Tichitt','Oasis 2','No','Yes'),
	array('Tichitt','Oasis 3','No','Yes'),
	array('Tichitt','Oasis 4','No','Yes'),
	array('Tichitt','Oasis 5','No','Yes'),
	array('Tavdeni','Walata','No','Yes'),
	array('Tavdeni','Kumbi Saleh','No','Yes'),
	array('Tavdeni','Timbuktu','No','Yes'),
	array('Tavdeni','Tadmekka','No','Yes'),
	array('Tavdeni','Ghat','No','Yes'),
	array('Tavdeni','Oasis 1','No','Yes'),
	array('Tavdeni','Oasis 2','No','Yes'),
	array('Tavdeni','Oasis 3','No','Yes'),
	array('Tavdeni','Oasis 4','No','Yes'),
	array('Tavdeni','Oasis 5','No','Yes'),
	array('Walata','Kumbi Saleh','No','Yes'),
	array('Walata','Niani','No','Yes'),
	array('Walata','Jenne','No','Yes'),
	array('Walata','Timbuktu','No','Yes'),
	array('Kumbi Saleh','Niani','No','Yes'),
	array('Niani','Jenne','No','Yes'),
	array('Jenne','Timbuktu','No','Yes'),
	array('Jenne','Tadmekka','No','Yes'),
	array('Jenne','Gwandu','No','Yes'),
	array('Jenne','Mossi','No','Yes'),
	array('Timbuktu','Tadmekka','No','Yes'),
	array('Tadmekka','Gao','No','Yes'),
	array('Tadmekka','Ghat','No','Yes'),
	array('Tadmekka','Takedda','No','Yes'),
	array('Tadmekka','Gwandu','No','Yes'),
	array('Gao','Ghat','No','Yes'),
	array('Gao','Takedda','No','Yes'),
	array('Ghat','Murzuk','No','Yes'),
	array('Ghat','Bilma','No','Yes'),
	array('Ghat','Agadez','No','Yes'),
	array('Ghat','Takedda','No','Yes'),
	array('Ghat','Oasis 1','No','Yes'),
	array('Ghat','Oasis 2','No','Yes'),
	array('Ghat','Oasis 3','No','Yes'),
	array('Ghat','Oasis 4','No','Yes'),
	array('Ghat','Oasis 5','No','Yes'),
	array('Murzuk','Tibesti','No','Yes'),
	array('Murzuk','Bilma','No','Yes'),
	array('Murzuk','Oasis 1','No','Yes'),
	array('Murzuk','Oasis 2','No','Yes'),
	array('Murzuk','Oasis 3','No','Yes'),
	array('Murzuk','Oasis 4','No','Yes'),
	array('Murzuk','Oasis 5','No','Yes'),
	array('Tibesti','Abesehr','No','Yes'),
	array('Tibesti','Bilma','No','Yes'),
	array('Tibesti','Oasis 1','No','Yes'),
	array('Tibesti','Oasis 2','No','Yes'),
	array('Tibesti','Oasis 3','No','Yes'),
	array('Tibesti','Oasis 4','No','Yes'),
	array('Tibesti','Oasis 5','No','Yes'),
	array('Abesehr','Ubangi','No','Yes'),
	array('Abesehr','Bouar','No','Yes'),
	array('Abesehr','Masseniya','No','Yes'),
	array('Abesehr','Bilma','No','Yes'),
	array('Ubangi','Lunda','No','Yes'),
	array('Ubangi','Kongo','No','Yes'),
	array('Ubangi','Bouar','No','Yes'),
	array('Lunda','Kongo','No','Yes'),
	array('Lunda','Wouri','Yes','Yes'),
	array('Lunda','Bight of Biafra','Yes','No'),
	array('Lunda','High Seas 1','Yes','No'),
	array('Lunda','High Seas 2','Yes','No'),
	array('Lunda','High Seas 3','Yes','No'),
	array('Kongo','Wouri','No','Yes'),
	array('Kongo','Bouar','No','Yes'),
	array('Wouri','Zazzau','No','Yes'),
	array('Wouri','Bouar','No','Yes'),
	array('Wouri','Owo','Yes','Yes'),
	array('Wouri','Bight of Biafra','Yes','No'),
	array('Zazzau','Bouar','No','Yes'),
	array('Zazzau','Masseniya','No','Yes'),
	array('Zazzau','Njimi','No','Yes'),
	array('Zazzau','Agadez','No','Yes'),
	array('Zazzau','Ife','No','Yes'),
	array('Zazzau','Nupe','No','Yes'),
	array('Zazzau','Owo','No','Yes'),
	array('Bouar','Masseniya','No','Yes'),
	array('Masseniya','Bilma','No','Yes'),
	array('Masseniya','Njimi','No','Yes'),
	array('Bilma','Njimi','No','Yes'),
	array('Bilma','Agadez','No','Yes'),
	array('Njimi','Agadez','No','Yes'),
	array('Agadez','Takedda','No','Yes'),
	array('Agadez','Oyo','No','Yes'),
	array('Agadez','Nupe','No','Yes'),
	array('Takedda','Gwandu','No','Yes'),
	array('Takedda','Oyo','No','Yes'),
	array('Gwandu','Oagadougou','No','Yes'),
	array('Gwandu','Mossi','No','Yes'),
	array('Gwandu','Salaga','No','Yes'),
	array('Gwandu','Oyo','No','Yes'),
	array('Oagadougou','Mossi','No','Yes'),
	array('Mossi','Begho','No','Yes'),
	array('Mossi','Salaga','No','Yes'),
	array('Begho','Salaga','No','Yes'),
	array('Begho','Bono Manso','Yes','Yes'),
	array('Begho','Sea of Bure','Yes','No'),
	array('Begho','Akan Sea','Yes','No'),
	array('Salaga','Bono Manso','No','Yes'),
	array('Salaga','Oyo','No','Yes'),
	array('Salaga','Ijebu','No','Yes'),
	array('Bono Manso','Ijebu','Yes','Yes'),
	array('Bono Manso','Akan Sea','Yes','No'),
	array('Oyo','Ijebu','No','Yes'),
	array('Oyo','Ife','No','Yes'),
	array('Oyo','Nupe','No','Yes'),
	array('Ijebu','Edo','Yes','Yes'),
	array('Ijebu','Ife','No','Yes'),
	array('Ijebu','Akan Sea','Yes','No'),
	array('Ijebu','Bight of Biafra','Yes','No'),
	array('Edo','Ife','No','Yes'),
	array('Edo','Owo','Yes','Yes'),
	array('Edo','Bight of Biafra','Yes','No'),
	array('Ife','Nupe','No','Yes'),
	array('Ife','Owo','No','Yes'),
	array('Owo','Bight of Biafra','Yes','No'),
	array('Etula Eri','Bight of Biafra','Yes','No'),
	array('Etula Eri','High Seas 1','Yes','No'),
	array('Etula Eri','High Seas 2','Yes','No'),
	array('Etula Eri','High Seas 3','Yes','No'),
	array('Oasis 1','Oasis 2','No','Yes'),
	array('Oasis 1','Oasis 3','No','Yes'),
	array('Oasis 1','Oasis 4','No','Yes'),
	array('Oasis 1','Oasis 5','No','Yes'),
	array('Oasis 2','Oasis 3','No','Yes'),
	array('Oasis 2','Oasis 4','No','Yes'),
	array('Oasis 2','Oasis 5','No','Yes'),
	array('Oasis 3','Oasis 4','No','Yes'),
	array('Oasis 3','Oasis 5','No','Yes'),
	array('Oasis 4','Oasis 5','No','Yes'),
	array('Jolof Sea','Sea of Wangara','Yes','No'),
	array('Jolof Sea','High Seas 1','Yes','No'),
	array('Jolof Sea','High Seas 2','Yes','No'),
	array('Jolof Sea','High Seas 3','Yes','No'),
	array('Sea of Wangara','Sea of Bure','Yes','No'),
	array('Sea of Wangara','High Seas 1','Yes','No'),
	array('Sea of Wangara','High Seas 2','Yes','No'),
	array('Sea of Wangara','High Seas 3','Yes','No'),
	array('Sea of Bure','Akan Sea','Yes','No'),
	array('Sea of Bure','High Seas 1','Yes','No'),
	array('Sea of Bure','High Seas 2','Yes','No'),
	array('Sea of Bure','High Seas 3','Yes','No'),
	array('Akan Sea','Bight of Biafra','Yes','No'),
	array('Akan Sea','High Seas 1','Yes','No'),
	array('Akan Sea','High Seas 2','Yes','No'),
	array('Akan Sea','High Seas 3','Yes','No'),
	array('Bight of Biafra','High Seas 1','Yes','No'),
	array('Bight of Biafra','High Seas 2','Yes','No'),
	array('Bight of Biafra','High Seas 3','Yes','No'),
	array('High Seas 1','High Seas 2','Yes','No'),
	array('High Seas 1','High Seas 3','Yes','No'),
	array('High Seas 2','High Seas 3','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
